# .github/workflows/dev.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Makes CI
on: [push, pull_request]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: helloWorld
        with:
          args: skims --strict scan . 
